# Cloud Build configuration for IPTC API
# 
# Required substitutions (set in Cloud Build trigger or command line):
#   _REGION: Cloud Run region (e.g., asia-northeast1)
#   _SERVICE_NAME: Cloud Run service name (e.g., iptc-api)
#   _IPTC_API_KEY: API key for authentication
#   _ALLOWED_ORIGINS: Comma-separated list of allowed CORS origins
#
# Example command:
#   gcloud builds submit --config=cloudbuild.yaml \
#     --substitutions=_REGION=asia-northeast1,_SERVICE_NAME=iptc-api,_IPTC_API_KEY=your-api-key,_ALLOWED_ORIGINS=https://your-app.vercel.app

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'
    dir: 'cloud-run'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    dir: 'cloud-run'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    dir: 'cloud-run'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--set-env-vars'
      - 'IPTC_API_KEY=${_IPTC_API_KEY},ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Substitution defaults (can be overridden)
substitutions:
  _REGION: 'asia-northeast1'
  _SERVICE_NAME: 'iptc-api'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

